languageCode = "en"
languageName = "English"
weight = 1
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

title = "Evin Li"
description = "Evin Li's Web Portfolio"

[author]
  name = "Evin Li"
  image = "img/profile.png"
  headline = "5th Year Engineering Physics @ UBC"
  links = [
    { email = "mailto:evinywli@gmail.com" },
    { github = "https://github.com/evinli" },
    { linkedin = "https://www.linkedin.com/in/evin-li-162905190/" }
  ]
